name: an_open_soul_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  characters: ^1.3.0
  collection: ^1.19.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path_provider: ^2.1.5
  vibration: ^3.1.3
  camera: ^0.11.1
  path: ^1.9.0
  logger: ^2.5.0
  video_player: ^2.9.2
  image_gallery_saver: ^2.0.3
  video_thumbnail: ^0.5.0
  flutter_image_compress: ^2.0.3
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  intl: any
  table_calendar: ^3.0.2
  image_cropper: ^9.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.0+1
  firebase_storage: ^12.4.4
  url_launcher: ^6.2.5
  animate_do: ^4.2.0
  flutter_local_notifications: ^16.1.0
  lottie: ^2.2.0
  overlay_support: ^1.2.1
  audioplayers: ^6.2.0
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.5
  http: ^1.1.0
  in_app_purchase: ^3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/emojis/very_bad.gif
    - assets/emojis/bad.gif
    - assets/emojis/neutral.gif
    - assets/emojis/okay.gif
    - assets/emojis/excellent.gif
    - assets/images/heart.png
    - assets/images/laugh.png
    - assets/images/sad.png
    - assets/images/angry.png
    - assets/images/like.png
    - assets/success.json
    - assets/images/nova_avatar.png
