// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMwVsQuJCcPcKvHM4DGhDD5h3nTcGcdI',
    appId: '1:128090321920:web:f02859f4c2d710a811d4e5',
    messagingSenderId: '128090321920',
    projectId: 'an-open-soul',
    authDomain: 'an-open-soul.firebaseapp.com',
    storageBucket: 'an-open-soul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rxs3NyepCGbtAcrPLVBXhChA6R6wR44',
    appId: '1:128090321920:android:520c4971de015a6711d4e5',
    messagingSenderId: '128090321920',
    projectId: 'an-open-soul',
    storageBucket: 'an-open-soul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL9WaK9CPBCVcAZka9uMughr29FNGsz0',
    appId: '1:128090321920:ios:d7b1128419f6ae3811d4e5',
    messagingSenderId: '128090321920',
    projectId: 'an-open-soul',
    storageBucket: 'an-open-soul.firebasestorage.app',
    iosBundleId: 'com.anopensoul.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAL9WaK9CPBCVcAZka9uMughr29FNGsz0',
    appId: '1:128090321920:ios:3f195026afd6808111d4e5',
    messagingSenderId: '128090321920',
    projectId: 'an-open-soul',
    storageBucket: 'an-open-soul.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIMwVsQuJCcPcKvHM4DGhDD5h3nTcGcdI',
    appId: '1:128090321920:web:952c43b69c92687511d4e5',
    messagingSenderId: '128090321920',
    projectId: 'an-open-soul',
    authDomain: 'an-open-soul.firebaseapp.com',
    storageBucket: 'an-open-soul.firebasestorage.app',
  );

}